version: 2

jobs:
  build:
    docker:
      - image: cachednerds/rust-cargo-web:latest
    steps:
      - checkout
      - persist_to_workspace:
          root: "."

      - restore_cache:
          key: app-cache
#      - run:
#          name: Check formatting
#          command: |
#            rustfmt --version
#            cargo fmt -- --write-mode=diff
      - run:
          name: Nightly Build
          command: cargo web build --target=wasm32-unknown-unknown
          command: cargo web deploy --target=wasm32-unknown-unknown
      - persist_to_workspace:
          root: "."
          paths:
            - Cargo.lock
#      - run:
#          name: Stable Build
#          command: |
#            rustup run stable rustc --version --verbose
#            rustup run stable cargo --version --verbose
#            rustup run stable cargo build
#      - run:
#          name: Test
#          command: cargo test
#      - run:
#          name: Upload Coverage
#          command: ./scripts/codecov.sh
      - save_cache:
          key: app-cache
          paths:
            - "~/.cargo"
            - "./target"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          key: app-cache
      - run: npm i
      - run: npx surge /Users/mackenzieclark/dev/rustconf-scheduler/target/deploy rustconf_scheduler --domain rustconf-scheduler.surge.sh
#      - save_cache:
#          key: project-cache
#          paths:
#            - "./node_modules"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master