version: 2

jobs:
  build:
    working_directory: ~/rusconf-scheduler
    docker:
      - image: cachednerds/rust-cargo-web:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
#      - run:
#          name: Check formatting
#          command: |
#            rustfmt --version
#            cargo fmt -- --write-mode=diff
      - run:
          name: Nightly Build
          command: cargo web build --target=wasm32-unknown-unknown
#      - run:
#          name: Stable Build
#          command: |
#            rustup run stable rustc --version --verbose
#            rustup run stable cargo --version --verbose
#            rustup run stable cargo build
#      - run:
#          name: Test
#          command: cargo test
#      - run:
#          name: Upload Coverage
#          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "./target"
  deploy:
    working_directory: ~/rusconf-scheduler
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run: npm i
      - run: npx surge /Users/mackenzieclark/dev/rustconf-scheduler/target/deploy rustconf_scheduler --domain rustconf-scheduler.surge.sh
      - save_cache:
          key: project-cache
          paths:
            - "./node_modules"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master