version: 2

jobs:
  build:
    docker:
      - image: cachednerds/rust-cargo-web:latest

    environment:
      # Set your codecov token if your repository is private.
#      CODECOV_TOKEN: <your-token>
#      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
#      - run:
#          name: Check formatting
#          command: |
#            rustfmt --version
#            cargo fmt -- --write-mode=diff
      - run:
          name: Nightly Build
          command: cargo web build --target=wasm32-unknown-unknown
      - deployment:
          production:
            branch: master
            commands:
              - npx surge /Users/mackenzieclark/dev/rustconf-scheduler/target/deploy rustconf_scheduler --domain rustconf-scheduler.surge.sh

#      - run:
#          name: Stable Build
#          command: |
#            rustup run stable rustc --version --verbose
#            rustup run stable cargo --version --verbose
#            rustup run stable cargo build
#      - run:
#          name: Test
#          command: cargo test
#      - run:
#          name: Upload Coverage
#          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "./target"